"""add reminder templates to app_settings

Revision ID: a851bf6deac2
Revises: 4c67c2b3f2dc
Create Date: 2026-06-25 08:09:52.512890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a851bf6deac2'
down_revision: Union[str, None] = '4c67c2b3f2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        # 既存の app_settings 行のために server_default を付与する。
        batch_op.add_column(sa.Column(
            'reminder_due_template', sa.Text(), nullable=False,
            server_default='資産「{asset}」の返却期限（{due}）が近づいています',
        ))
        batch_op.add_column(sa.Column(
            'reminder_overdue_template', sa.Text(), nullable=False,
            server_default='資産「{asset}」の返却期限（{due}）を超過しています',
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('reminder_overdue_template')
        batch_op.drop_column('reminder_due_template')

    # ### end Alembic commands ###
